services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ..:/var/www
    expose:
      - "9000"
    links:
      - db
    depends_on:
      - db
    networks:
      - main

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ..:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - main

  db:
    image: postgres:18
    env_file: .env
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - main

volumes:
  postgres:

networks:
  main:
    driver: bridge
